package shared.domain.exceptions

class AlreadyUsedIdentifierException : Throwable()
